"""Regenerate src/lib/refs.py from the plate (.jscad) and the PCB (.kicad_pcb).

Run with KiCad's bundled Python (it needs `pcbnew`):

    /Applications/KiCad/KiCad.app/Contents/Frameworks/Python.framework/Versions/Current/bin/python3 \
        case/tools/extract_refs.py

Coordinates are written in the PLATE frame used by plate-88keys.jscad:
origin = centre of switch "0,0" (Esc), +X right, +Y towards the back (KiCad Y flipped).
"""
import math
import re
from pathlib import Path

import pcbnew

HERE = Path(__file__).resolve().parent
BOARD_DIR = HERE.parent.parent
JSCAD = BOARD_DIR / "plate-88keys.jscad"
PCB = BOARD_DIR / "alps75-zug.kicad_pcb"
OUT = HERE.parent / "src" / "lib" / "refs.py"

NUM = r"(-?[\d.]+)"


def parse_plate(text):
    thickness = float(re.search(r"const THICKNESS = " + NUM, text).group(1))
    m = re.search(
        r"const outline = translate\(\[" + NUM + ", " + NUM + r", 0\], roundedRectangle\(\{ size: \["
        + NUM + ", " + NUM + r"\], roundRadius: " + NUM,
        text,
    )
    outline = tuple(float(v) for v in m.groups())
    switch_size = tuple(
        float(v)
        for v in re.search(r"const switch_shape = roundedRectangle\(\{ size: \[" + NUM + ", " + NUM, text).groups()
    )
    stab_size = tuple(
        float(v)
        for v in re.search(r"const stab_pad = roundedRectangle\(\{ size: \[" + NUM + ", " + NUM, text).groups()
    )
    switches = []
    for line in text.splitlines():
        m = re.match(r"const switch_\d+ = (.*)//\s*\"(\d+),(\d+)\" ([\d.]+)u", line)
        if not m:
            continue
        body, width = m.group(1), float(m.group(4))
        t = re.search(r"translate\(\[" + NUM + ", " + NUM, body)
        x, y = (float(t.group(1)), float(t.group(2))) if t else (0.0, 0.0)
        switches.append((x, y, "rotateZ" in body, width))
    stabs = [
        (float(a), float(b))
        for a, b in re.findall(r"const stab_\d+_[ab] = translate\(\[" + NUM + ", " + NUM, text)
    ]
    holes = [
        (float(a), float(b), float(r))
        for a, b, r in re.findall(
            r"const (?:hole|customHole)\w* = translate\(\[" + NUM + ", " + NUM + r", 0\], circle\(\{ radius: " + NUM,
            text,
        )
    ]
    rects = {}
    for name in ("picoUsbNotch", "picoBootsel"):
        m = re.search(
            "const " + name + r" = translate\(\[" + NUM + ", " + NUM + r", 0\], roundedRectangle\(\{ size: \["
            + NUM + ", " + NUM + r"\], roundRadius: " + NUM,
            text,
        )
        rects[name] = tuple(float(v) for v in m.groups())
    return thickness, outline, switch_size, stab_size, switches, stabs, holes, rects


def parse_pcb():
    b = pcbnew.LoadBoard(str(PCB))
    mm = pcbnew.ToMM
    sw0 = next(f for f in b.GetFootprints() if f.GetReference() == "SW1").GetPosition()
    x0, y0 = mm(sw0.x), mm(sw0.y)

    def p(v):
        return (round(mm(v.x) - x0, 4), round(y0 - mm(v.y), 4))

    # Chain the Edge.Cuts segments into one closed polygon (arcs -> midpoint-sampled).
    segs = []
    for d in b.GetDrawings():
        if d.GetLayerName() != "Edge.Cuts":
            continue
        if d.GetShapeStr() == "Arc":
            c = d.GetCenter()
            r = mm(d.GetRadius())
            a0 = math.atan2(mm(d.GetStart().y - c.y), mm(d.GetStart().x - c.x))
            a1 = math.atan2(mm(d.GetEnd().y - c.y), mm(d.GetEnd().x - c.x))
            da = (a1 - a0 + math.pi) % (2 * math.pi) - math.pi
            pts = [
                (round(mm(c.x) + r * math.cos(a0 + da * k / 4) - x0, 4), round(y0 - (mm(c.y) + r * math.sin(a0 + da * k / 4)), 4))
                for k in range(5)
            ]
            segs.append(pts)
        else:
            segs.append([p(d.GetStart()), p(d.GetEnd())])
    poly = list(segs.pop(0))
    close = lambda a, b: abs(a[0] - b[0]) < 1e-3 and abs(a[1] - b[1]) < 1e-3
    while segs:
        for i, s in enumerate(segs):
            if close(s[0], poly[-1]):
                poly += s[1:]
            elif close(s[-1], poly[-1]):
                poly += list(reversed(s))[1:]
            else:
                continue
            segs.pop(i)
            break
        else:
            raise SystemExit("Edge.Cuts is not a single closed loop")
    if close(poly[0], poly[-1]):
        poly.pop()
    u1 = next(f for f in b.GetFootprints() if f.GetReference() == "U1")
    thickness = mm(b.GetDesignSettings().GetBoardThickness())
    return thickness, poly, p(u1.GetPosition())


def main():
    thickness, outline, switch_size, stab_size, switches, stabs, holes, rects = parse_plate(JSCAD.read_text())
    pcb_t, pcb_poly, pico = parse_pcb()
    lines = [
        '"""Reference geometry extracted from the plate and PCB. GENERATED by tools/extract_refs.py -- do not edit.',
        "",
        "Plate frame: origin at the centre of switch \"0,0\" (Esc), +X right, +Y to the back, mm.",
        '"""',
        "",
        f"PLATE_THICKNESS = {thickness}",
        f"# (centre_x, centre_y, width, depth, corner_radius)",
        f"PLATE_OUTLINE = {outline}",
        f"SWITCH_CUTOUT = {switch_size}  # (x, y) before rotation",
        f"STAB_CUTOUT = {stab_size}",
        "# (x, y, rotated_90, width_in_units)",
        "SWITCHES = (",
        *[f"    {s}," for s in switches],
        ")",
        "STABS = (",
        *[f"    {s}," for s in stabs],
        ")",
        "# (x, y, radius) -- the plate's M3 mounting holes",
        "PLATE_HOLES = (",
        *[f"    {h}," for h in holes],
        ")",
        "# (centre_x, centre_y, width, depth, corner_radius)",
        f"PICO_USB_NOTCH = {rects['picoUsbNotch']}",
        f"PICO_BOOTSEL = {rects['picoBootsel']}",
        "",
        f"PCB_THICKNESS = {pcb_t}",
        "# Board outline (Edge.Cuts), counter-clockwise or clockwise, closed implicitly",
        "PCB_OUTLINE = (",
        *[f"    {pt}," for pt in pcb_poly],
        ")",
        f"PICO_CENTER = {pico}  # U1 footprint origin, Pico long axis along X, USB end at -X",
        "",
    ]
    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT} ({len(switches)} switches, {len(holes)} holes, {len(pcb_poly)} outline points)")


if __name__ == "__main__":
    main()
