/**
 * Keyboard Plate - Generated by KLE-NG
 *
 * Cutout type: alps-skcm
 * Stabilizer type: alps-aek
 * Plate thickness: 1.2 mm
 * Generated: 2026-09-18
 *
 * This file uses the @jscad/modeling API (OpenJSCAD v2).
 * Open with: https://openjscad.xyz/
 */
const jscad = require('@jscad/modeling')
const { circle, polygon, roundedRectangle } = jscad.primitives
const { rotateZ, translate } = jscad.transforms
const { extrudeLinear } = jscad.extrusions
const { subtract, union } = jscad.booleans

const THICKNESS = 1.2 // mm

// --- Plate outline ---
// Sized to the PCB (x 37.08..372.5, y 85.5..242.025 in KiCad coords) plus a 7.5 mm border
// so every mounting hole sits 3.5 mm outside the PCB edge.
const outline = translate([149.959, -32.512, 0], roundedRectangle({ size: [350.42, 171.525], roundRadius: 4 }))

// --- Shared shapes ---
const switch_shape = roundedRectangle({ size: [15.5, 12.8], roundRadius: 0.5 })
const stab_pad = roundedRectangle({ size: [2.67, 5.21], roundRadius: 0.5 })

// --- Switch cutouts ---
const switch_0 = rotateZ(1.571, switch_shape)  // "0,0" 1u
const switch_1 = translate([19.05, 0, 0], rotateZ(1.571, switch_shape))  // "0,1" 1u
const switch_2 = translate([38.1, 0, 0], rotateZ(1.571, switch_shape))  // "0,2" 1u
const switch_3 = translate([57.15, 0, 0], rotateZ(1.571, switch_shape))  // "0,3" 1u
const switch_4 = translate([76.2, 0, 0], rotateZ(1.571, switch_shape))  // "0,4" 1u
const switch_5 = translate([95.25, 0, 0], rotateZ(1.571, switch_shape))  // "0,5" 1u
const switch_6 = translate([114.3, 0, 0], rotateZ(1.571, switch_shape))  // "0,6" 1u
const switch_7 = translate([133.35, 0, 0], rotateZ(1.571, switch_shape))  // "0,7" 1u
const switch_8 = translate([152.4, 0, 0], rotateZ(1.571, switch_shape))  // "0,8" 1u
const switch_9 = translate([171.45, 0, 0], rotateZ(1.571, switch_shape))  // "0,9" 1u
const switch_10 = translate([190.5, 0, 0], rotateZ(1.571, switch_shape))  // "0,10" 1u
const switch_11 = translate([209.55, 0, 0], rotateZ(1.571, switch_shape))  // "0,11" 1u
const switch_12 = translate([228.6, 0, 0], rotateZ(1.571, switch_shape))  // "0,12" 1u
const switch_13 = translate([247.65, 0, 0], rotateZ(1.571, switch_shape))  // "0,13" 1u
const switch_14 = translate([266.7, 0, 0], rotateZ(1.571, switch_shape))  // "0,14" 1u
const switch_15 = translate([285.75, 0, 0], rotateZ(1.571, switch_shape))  // "0,15" 1u
const switch_16 = translate([304.8, 0, 0], rotateZ(1.571, switch_shape))  // "0,16" 1u
const switch_17 = translate([0, -19.05, 0], switch_shape)  // "1,0" 1u
const switch_18 = translate([19.05, -19.05, 0], switch_shape)  // "1,1" 1u
const switch_19 = translate([38.1, -19.05, 0], switch_shape)  // "1,2" 1u
const switch_20 = translate([57.15, -19.05, 0], switch_shape)  // "1,3" 1u
const switch_21 = translate([76.2, -19.05, 0], switch_shape)  // "1,4" 1u
const switch_22 = translate([95.25, -19.05, 0], switch_shape)  // "1,5" 1u
const switch_23 = translate([114.3, -19.05, 0], switch_shape)  // "1,6" 1u
const switch_24 = translate([133.35, -19.05, 0], switch_shape)  // "1,7" 1u
const switch_25 = translate([152.4, -19.05, 0], switch_shape)  // "1,8" 1u
const switch_26 = translate([171.45, -19.05, 0], switch_shape)  // "1,9" 1u
const switch_27 = translate([190.5, -19.05, 0], switch_shape)  // "1,10" 1u
const switch_28 = translate([209.55, -19.05, 0], switch_shape)  // "1,11" 1u
const switch_29 = translate([228.6, -19.05, 0], switch_shape)  // "1,12" 1u
const switch_30 = translate([257.175, -19.05, 0], switch_shape)  // "1,13" 2u
const switch_31 = translate([285.75, -19.05, 0], switch_shape)  // "1,15" 1u
const switch_32 = translate([304.8, -19.05, 0], switch_shape)  // "1,16" 1u
const switch_33 = translate([4.763, -38.1, 0], switch_shape)  // "2,0" 1.5u
const switch_34 = translate([28.575, -38.1, 0], switch_shape)  // "2,1" 1u
const switch_35 = translate([47.625, -38.1, 0], switch_shape)  // "2,2" 1u
const switch_36 = translate([66.675, -38.1, 0], switch_shape)  // "2,3" 1u
const switch_37 = translate([85.725, -38.1, 0], switch_shape)  // "2,4" 1u
const switch_38 = translate([104.775, -38.1, 0], switch_shape)  // "2,5" 1u
const switch_39 = translate([123.825, -38.1, 0], switch_shape)  // "2,6" 1u
const switch_40 = translate([142.875, -38.1, 0], switch_shape)  // "2,7" 1u
const switch_41 = translate([161.925, -38.1, 0], switch_shape)  // "2,8" 1u
const switch_42 = translate([180.975, -38.1, 0], switch_shape)  // "2,9" 1u
const switch_43 = translate([200.025, -38.1, 0], switch_shape)  // "2,10" 1u
const switch_44 = translate([219.075, -38.1, 0], switch_shape)  // "2,11" 1u
const switch_45 = translate([238.125, -38.1, 0], switch_shape)  // "2,12" 1u
const switch_46 = translate([261.938, -38.1, 0], switch_shape)  // "2,13" 1.5u
const switch_47 = translate([285.75, -38.1, 0], switch_shape)  // "2,15" 1u
const switch_48 = translate([304.8, -38.1, 0], switch_shape)  // "2,16" 1u
const switch_49 = translate([7.144, -57.15, 0], switch_shape)  // "3,0" 1.75u
const switch_50 = translate([33.338, -57.15, 0], switch_shape)  // "3,1" 1u
const switch_51 = translate([52.388, -57.15, 0], switch_shape)  // "3,2" 1u
const switch_52 = translate([71.438, -57.15, 0], switch_shape)  // "3,3" 1u
const switch_53 = translate([90.488, -57.15, 0], switch_shape)  // "3,4" 1u
const switch_54 = translate([109.538, -57.15, 0], switch_shape)  // "3,5" 1u
const switch_55 = translate([128.588, -57.15, 0], switch_shape)  // "3,6" 1u
const switch_56 = translate([147.638, -57.15, 0], switch_shape)  // "3,7" 1u
const switch_57 = translate([166.688, -57.15, 0], switch_shape)  // "3,8" 1u
const switch_58 = translate([185.738, -57.15, 0], switch_shape)  // "3,9" 1u
const switch_59 = translate([204.788, -57.15, 0], switch_shape)  // "3,10" 1u
const switch_60 = translate([223.838, -57.15, 0], switch_shape)  // "3,11" 1u
const switch_61 = translate([254.794, -57.15, 0], switch_shape)  // "3,13" 2.25u
const switch_62 = translate([285.75, -57.15, 0], switch_shape)  // "3,15" 1u
const switch_63 = translate([304.8, -57.15, 0], switch_shape)  // "3,16" 1u
const switch_64 = translate([11.906, -76.2, 0], switch_shape)  // "4,0" 2.25u
const switch_65 = translate([42.863, -76.2, 0], switch_shape)  // "4,2" 1u
const switch_66 = translate([61.913, -76.2, 0], switch_shape)  // "4,3" 1u
const switch_67 = translate([80.963, -76.2, 0], switch_shape)  // "4,4" 1u
const switch_68 = translate([100.013, -76.2, 0], switch_shape)  // "4,5" 1u
const switch_69 = translate([119.063, -76.2, 0], switch_shape)  // "4,6" 1u
const switch_70 = translate([138.113, -76.2, 0], switch_shape)  // "4,7" 1u
const switch_71 = translate([157.163, -76.2, 0], switch_shape)  // "4,8" 1u
const switch_72 = translate([176.213, -76.2, 0], switch_shape)  // "4,9" 1u
const switch_73 = translate([195.263, -76.2, 0], switch_shape)  // "4,10" 1u
const switch_74 = translate([214.313, -76.2, 0], switch_shape)  // "4,11" 1u
const switch_75 = translate([250.031, -76.2, 0], switch_shape)  // "4,13" 2.75u
const switch_76 = translate([285.75, -76.2, 0], switch_shape)  // "4,15" 1u
const switch_77 = translate([304.8, -76.2, 0], switch_shape)  // "4,16" 1u
const switch_78 = translate([4.763, -95.25, 0], switch_shape)  // "5,0" 1.5u
const switch_79 = translate([30.956, -95.25, 0], switch_shape)  // "5,1" 1.25u
const switch_80 = translate([57.15, -95.25, 0], switch_shape)  // "5,3" 1.5u
const switch_81 = translate([133.35, -95.25, 0], switch_shape)  // "5,7" 6.5u
const switch_82 = translate([207.169, -95.25, 0], switch_shape)  // "5,10" 1.25u
const switch_83 = translate([228.6, -95.25, 0], switch_shape)  // "5,12" 1u
const switch_84 = translate([247.65, -95.25, 0], switch_shape)  // "5,13" 1u
const switch_85 = translate([266.7, -95.25, 0], switch_shape)  // "5,14" 1u
const switch_86 = translate([285.75, -95.25, 0], switch_shape)  // "5,15" 1u
const switch_87 = translate([304.8, -95.25, 0], switch_shape)  // "5,16" 1u

// --- Stabilizer cutouts ---
const stab_30_a = translate([243.175, -25.53, 0], stab_pad)
const stab_30_b = translate([271.175, -25.53, 0], stab_pad)
const stab_30 = union(stab_30_a, stab_30_b)  // stabilizer for "1,13" (switch 30)
const stab_49_a = translate([-4.856, -63.63, 0], stab_pad)
const stab_49_b = translate([19.144, -63.63, 0], stab_pad)
const stab_49 = union(stab_49_a, stab_49_b)  // stabilizer for "3,0" (switch 49)
const stab_61_a = translate([240.794, -63.63, 0], stab_pad)
const stab_61_b = translate([268.794, -63.63, 0], stab_pad)
const stab_61 = union(stab_61_a, stab_61_b)  // stabilizer for "3,13" (switch 61)
const stab_64_a = translate([-2.094, -82.68, 0], stab_pad)
const stab_64_b = translate([25.906, -82.68, 0], stab_pad)
const stab_64 = union(stab_64_a, stab_64_b)  // stabilizer for "4,0" (switch 64)
const stab_75_a = translate([236.031, -82.68, 0], stab_pad)
const stab_75_b = translate([264.031, -82.68, 0], stab_pad)
const stab_75 = union(stab_75_a, stab_75_b)  // stabilizer for "4,13" (switch 75)
const stab_81_a = translate([88.05, -101.73, 0], stab_pad)
const stab_81_b = translate([178.65, -101.73, 0], stab_pad)
const stab_81 = union(stab_81_a, stab_81_b)  // stabilizer for "5,7" (switch 81)

// --- Holes ---
const holeBottomLeft = translate([-21.251, -114.275, 0], circle({ radius: 1.6 }))
const holeBottomRight = translate([321.169, -114.275, 0], circle({ radius: 1.6 }))
const holeTopLeft = translate([-21.251, 49.25, 0], circle({ radius: 1.6 }))
const holeTopRight = translate([321.169, 49.25, 0], circle({ radius: 1.6 }))
// Custom holes: aligned with the corner holes, clockwise from top-left.
// Top/bottom edges split into equal thirds, left/right edges split in half.
const customHole_0 = translate([92.889, 49.25, 0], circle({ radius: 1.6 }))  // top
const customHole_1 = translate([207.029, 49.25, 0], circle({ radius: 1.6 }))  // top
const customHole_2 = translate([321.169, -32.512, 0], circle({ radius: 1.6 }))  // right
const customHole_3 = translate([207.029, -114.275, 0], circle({ radius: 1.6 }))  // bottom
const customHole_4 = translate([92.889, -114.275, 0], circle({ radius: 1.6 }))  // bottom
const customHole_5 = translate([-21.251, -32.512, 0], circle({ radius: 1.6 }))  // left

// --- Raspberry Pi Pico (U1, SMD on PCB top, under the plate) ---
// Plate underside is 3.3 mm above the PCB (Alps: 4.5 mm PCB-to-plate-top, 1.2 mm plate).
// Only the micro-USB receptacle (~3.7 mm) and BOOTSEL button (~3.5 mm) are taller than
// that; the rest of the Pico is <= ~2.6 mm and stays under solid plate.
// USB notch: the plate edge is 7.5 mm left of the PCB, so the micro-USB plug overmold
// (~11 x 7 mm, reaching ~6 mm above the PCB) passes through the plate plane. 13 mm tall,
// from past the plate edge to the receptacle's inner end + 0.8 mm (PCB x 42.2).
const picoUsbNotch = translate([-19.941, 30.05, 0], roundedRectangle({ size: [14.62, 13], roundRadius: 1 }))
// BOOTSEL access: button body 4.25 x 3.2 mm centred at (-5.751, 26.55), opening 8 x 7 mm.
const picoBootsel = translate([-5.751, 26.55, 0], roundedRectangle({ size: [8, 7], roundRadius: 1 }))

// --- Assembly ---
const allCutouts = union(
  switch_0,
  switch_1,
  switch_2,
  switch_3,
  switch_4,
  switch_5,
  switch_6,
  switch_7,
  switch_8,
  switch_9,
  switch_10,
  switch_11,
  switch_12,
  switch_13,
  switch_14,
  switch_15,
  switch_16,
  switch_17,
  switch_18,
  switch_19,
  switch_20,
  switch_21,
  switch_22,
  switch_23,
  switch_24,
  switch_25,
  switch_26,
  switch_27,
  switch_28,
  switch_29,
  switch_30,
  stab_30,
  switch_31,
  switch_32,
  switch_33,
  switch_34,
  switch_35,
  switch_36,
  switch_37,
  switch_38,
  switch_39,
  switch_40,
  switch_41,
  switch_42,
  switch_43,
  switch_44,
  switch_45,
  switch_46,
  switch_47,
  switch_48,
  switch_49,
  stab_49,
  switch_50,
  switch_51,
  switch_52,
  switch_53,
  switch_54,
  switch_55,
  switch_56,
  switch_57,
  switch_58,
  switch_59,
  switch_60,
  switch_61,
  stab_61,
  switch_62,
  switch_63,
  switch_64,
  stab_64,
  switch_65,
  switch_66,
  switch_67,
  switch_68,
  switch_69,
  switch_70,
  switch_71,
  switch_72,
  switch_73,
  switch_74,
  switch_75,
  stab_75,
  switch_76,
  switch_77,
  switch_78,
  switch_79,
  switch_80,
  switch_81,
  stab_81,
  switch_82,
  switch_83,
  switch_84,
  switch_85,
  switch_86,
  switch_87,
  holeBottomLeft,
  holeBottomRight,
  holeTopLeft,
  holeTopRight,
  customHole_0,
  customHole_1,
  customHole_2,
  customHole_3,
  customHole_4,
  customHole_5,
  picoUsbNotch,
  picoBootsel
)
const plate2d = subtract(outline, allCutouts)
const plate3d = extrudeLinear({ height: THICKNESS }, plate2d)
const finalPlate = plate3d

const main = () => finalPlate

module.exports = { main }